project:
  type: website
  render:
    - "*.md"
    - "README.md"
    - "digital-communications/README.md"
    - "research-data-management/README.md"
    - "gis-software/README.md"
    - "unix-shells-and-clis/README.md"
    - "development-environments/README.md"
    - "python/README.md"
    - "r/README.md"
    - "javascript/README.md"
    - "julia/README.md"
    - "databases/README.md"
    - "version-control-systems/README.md"
    - "high-performance-computing/README.md"
    - "cloud-computing/README.md"
    - "containers/README.md"
    - "xr/README.md"
    - "404.qmd"

website:
  title: "UBC Geography Computing Resources"
  favicon: "favicon.png"
  site-url: "https://ubc-geography.github.io/computing-resources"
  page-footer:
    center: |
      <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/80x15.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.
  open-graph:
    title: "UBC Geography Computing Resources"
    description:
      "A listing of computing resources and accompanying documentation that can
      be helpful in familiarizing oneself with various tools and software that
      are used in Geography research, instruction, and learning."
    locale: "en_US"
    image: "https://avatars.githubusercontent.com/u/101839150?s=400&u=adcfa46cecc67f714d828dcb66a26a6d1093d8bd&v=4"
    image-alt: UBC Geography logo
  repo-url: "https://github.com/UBC-Geography/computing-resources"
  repo-actions:
    - edit
    - issue
  sidebar:
    logo: "/assets/images/white-logo.png"
    logo-href: "https://geog.ubc.ca"
    title: "Computing Resources"
    style: floating
    search: true
    collapse-level: 1
    contents:
      - text: Home
        href: "index.html"
      - href: "digital-communications/index.html"
        text: Digital Communications
      - section: Research Data Management
        contents:
          - href: "research-data-management/index.html"
            text: Overview
          - href: "research-data-management/research-data-storage.html"
            text: Research Data Storage
      - href: "gis-software/index.html"
        text: GIS Software
      - href: "unix-shells-and-clis/index.html"
        text: UNIX Shells and CLIs
      - section: Development Environments
        contents:
          - href: "development-environments/index.html"
            text: Overview
          - href: "development-environments/conda-getting-started.html"
            text: Conda - Getting Started
          - href: "development-environments/jupyterhub-installing-packages.html"
            text: JupyterHub - Installing Packages
          - href: "development-environments/containerized-environments.html"
            text: Containerized Environments
      - href: "python/index.html"
        text: Python
      - href: "r/index.html"
        text: R
      - href: "javascript/index.html"
        text: JavaScript
      - href: "julia/index.html"
        text: Julia
      - href: "databases/index.html"
        text: Databases
      - section: Version Control Systems
        contents:
          - href: "version-control-systems/index.html"
            text: Overview
          - href: "version-control-systems/jupyterhub-private-repo.html"
            text: Working with Private GitHub Repositories from JupyterHub
      - section:
          High-Performance Computing (HPC) / High-Throughput Computing (HTC)
        contents:
          - href: "high-performance-computing/index.html"
            text: Overview
          - href: "high-performance-computing/running-isca.html"
            text: Running Isca
          - href: "high-performance-computing/running-cesm.html"
            text: Running CESM
      - section: Cloud Computing
        contents:
          - href: "cloud-computing/index.html"
            text: Overview
          - href: "cloud-computing/object-storage.html"
            text: Object Storage
          - href: "cloud-computing/deploying-a-dashboard.html"
            text: Deploying a Dashboard
          - href: "cloud-computing/deploying-omeka-classic.html"
            text: Deploying Omeka Classic
          - href: "cloud-computing/deploying-umap.html"
            text: Deploying uMap
      - href: "containers/index.html"
        text: Containers
      - href: "xr/index.html"
        text: "XR - Virtual Reality / Augmented Reality"

format:
  html:
    published-title: "Last Modified"
    theme:
      light: [sandstone, theme-light.scss]
      dark: [sandstone, theme-dark.scss]
    toc: true
    highlight-style: default
    canonical-url: true
    include-in-header:
      - text:
          <meta name="google-site-verification"
          content="J6iS77StTO4bFu1kqLjEiR5Q4BGI8EE0VKJzUbWw1ME" />

execute:
  freeze: auto
